var age = 25;
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'Luigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("Mario");
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "Mario", age: 5 };
console.log(ninja);
ninja = { name: 55, age: 'yushi' };
console.log(ninja);
